version: '3.1'
services:
  mysql:
    build: mysql
    container_name: mysql-laravelapi
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 41111:3306
  app:
    build: laravel
    container_name: app-laravelapi
    volumes:
      - ./laravel/src:/var/www/app
    ports:
      - 41112:8080
    links:
      - mysql
      - cache
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-laravelapi
    links:
      - mysql
    ports:
      - 41113:80
    environment:
      - PMA_ARBITRARY=1
  cache:
    image: redis:3.0
    ports:
      - "63791:6379"