FROM mysql:5.7

WORKDIR /tmp

ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=northwind

ADD ./arquivos/northwind-BR-MySQL.sql /tmp/northwind-BR-MySQL.sql

#mysqlimport -u root -proot northwind /tmp/northwind-BR-MySQL.sql

#mysql -proot -uroot northwind < /tmp/northwind-BR-MySQL.sql
